config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :genres
  resources :directors
  resources :movies do
    patch :publish, on: :member
    patch :withdraw_publication, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :genre
  has_many :movies
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :directors
  has_many :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  mount_uploader :poster, PosterUploader

  enum :release_status, { upcoming: 0, released: 1 }
  enum :status, { draft: 0, published: 1 }

  belongs_to :genre
  belongs_to :director

  def translate_release_status
    return "Já lançado" if release_status == "released"
    "A ser lançado"
  end

  def translate_status
    return "Rascunho" if status == "draft"
    "Publicado"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
    @movies = Movie.where(director_id: @director.id, status: :published)
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(name: params[:director][:name],
                    nationality: params[:director][:nationality],
                    birth_date: params[:director][:birth_date],
                    genre_id: params[:director][:genre_id],
                    biography: params[:director][:biography],
                  )

    if @director.save
      flash[:notice] = "Diretor(a) cadastrado(a) com sucesso."
      return redirect_to new_director_path
    end

    render :new
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])

    if @director.update(name: params[:director][:name],
                nationality: params[:director][:nationality],
                birth_date: params[:director][:birth_date],
                genre_id: params[:director][:genre_id],
                biography: params[:director][:biography],
              )

      flash[:notice] = "Diretor(a) editado(a) com sucesso."
      return redirect_to director_path(@director)
    end

    render :edit
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end
  def show
    @genre = Genre.find(params[:id])
    @movies = Movie.where(genre_id: @genre.id, status: :published)
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(name: params[:genre][:name],
                description: params[:genre][:description]
                )

    if @genre.save
      flash[:notice] = "Gênero cadastrado com sucesso."
      return redirect_to new_genre_path
    end

    render :new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(name: params[:genre][:name],
              description: params[:genre][:description]
            )

      flash[:notice] = "Gênero editado com sucesso."
      return redirect_to genre_path(@genre)
    end

    render :edit
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @released_movies = Movie.where(release_status: :released, status: :published)
    @upcoming_movies = Movie.where(release_status: :upcoming, status: :published)
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(name: params[:movie][:name],
                    country_of_origin: params[:movie][:country_of_origin],
                    release_year: params[:movie][:release_year],
                    length: params[:movie][:length],
                    genre_id: params[:movie][:genre_id],
                    director_id: params[:movie][:director_id],
                    release_status: params[:movie][:release_status],
                    poster: params[:movie][:poster],
                    synopse: params[:movie][:synopse],
                  )

    if @movie.save
      flash[:notice] = "Filme cadastrado com sucesso."
      return redirect_to new_movie_path
    end

    render :new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(name: params[:movie][:name],
                  country_of_origin: params[:movie][:country_of_origin],
                  release_year: params[:movie][:release_year],
                  length: params[:movie][:length],
                  genre_id: params[:movie][:genre_id],
                  director_id: params[:movie][:director_id],
                  release_status: params[:movie][:release_status],
                  poster: params[:movie][:poster],
                  synopse: params[:movie][:synopse],
                )

      flash[:notice] = "Filme editado com sucesso."
      return redirect_to movie_path(@movie)
    end

    render :edit
  end

  def publish
    movie = Movie.find(params[:id])
    movie.published!
    redirect_to movie_path(movie.id)
  end

  def withdraw_publication
    movie = Movie.find(params[:id])
    movie.draft!
    redirect_to movie_path(movie.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/_form.html.erb
<div>
  <%= form_with model: director do | f | %>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Nome: '%>
      <%= f.text_field :name %>
    </div>
    
    <div style="padding-bottom: 10px;">
      <%= f.label 'Nacionalidade: '%>
      <%= f.text_field :nationality %>
    </div>
    
    <div style="padding-bottom: 10px;">
      <%= f.label 'Data de nascimento: '%>
      <%= f.date_field :birth_date %>
    </div>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Gênero favorito: '%>
      <%= f.collection_select :genre_id, Genre.all, :id, :name %>
    </div>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Mini biografia: '%>
      <%= f.text_area :biography %>
    </div>

    <p><%= f.submit 'Cadastrar'%></p> 

  <% end %>
</div>

app/views/directors/edit.html.erb
<h2>Editar diretor(a)</h2>

<div>
  <%= render partial: 'form', locals: { director: @director } %>
</div>

<p><%= link_to 'Cancelar edição', director_path(@director) %></p>

app/views/directors/index.html.erb
<h1>Diretores</h1>

<div>
<h4><%= link_to 'Cadastrar novo diretor(a)', new_director_path %></h4>
</div>

<p><h4>Diretores cadastrados:</h4></p>

<div>
  <ul>
    <% @directors.each do | director |%>
      <li>
        <%= link_to director.name, director %>
      </li>
    <% end %>
  </ul>    
</div>

<div>
  <%= link_to 'Página inicial', root_path %>
</div>

app/views/directors/new.html.erb
<h2>Cadastro de diretores</h2>

<div>
  <% if flash[:notice] %>

    <div style="margin: 10px 0px">
      <%= flash[:notice] %>
    </div>

  <% end %>
</div>


<div>
  <%= render partial: 'form', locals: { director: @director } %>
</div>

<p><%= link_to 'Diretores', directors_path%></p>

app/views/directors/show.html.erb
<h1><%= @director.name %></h1>

<div style="margin: 10px 0px">
    <%= flash[:notice] %>
</div>

<div>
    <h3>Mini biografia:</h3>
    <p><%= @director.biography%></p>
</div>

<div style="padding-bottom: 10px;">
      <strong>Nacionalidade: </strong>
      <%= @director.nationality %>
</div>

<div style="padding-bottom: 10px;">
      <strong>Data de Nacimento: </strong>
      <%= @director.birth_date %>
</div>

<div style="padding-bottom: 10px;">
      <strong>Gênero favorito: </strong>
      <%= link_to @director.genre.name, genre_path(@director.genre.id) %>
</div>

<div>
  <% if @movies.any?%>
    <p><h3>Filmes dirigidos:</h3></p>
    <%= render partial: 'shared/movie', locals: {movies: @movies} %>
  <% else %>
    <div><h3>Não há filmes dirigidos por esse diretor(a).</h3></div>
    <div><%= link_to 'Cadastre um filme para este diretor(a)', new_movie_path %></div>
  <% end %>
</div>

<p><strong><%= link_to 'Editar diretor(a)', edit_director_path %></strong></p>

<p><%= link_to 'Diretores', directors_path%></p>

app/views/genres/_form.html.erb
<% if flash[:notice] %>

  <div style="margin: 10px 0px">
    <%= flash[:notice] %>
  </div>

<% end %>

<div>
  <%= form_with model: genre do | f | %>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Nome: '%>
      <%= f.text_field :name %>
    </div>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Descrição: '%>
      <%= f.text_area :description %>
    </div>

    <%= f.submit 'Cadastrar'%>

  <% end %>
</div>

app/views/genres/edit.html.erb
<h2>Editar gênero</h2>

<div>
  <%= render partial: 'form', locals: { genre: @genre } %>
</div>

<p><%= link_to 'Cancelar edição', genre_path(@genre) %></p>

app/views/genres/index.html.erb
<h1>Gêneros</h1>

<div>
<h4><%= link_to 'Cadastrar novo gênero', new_genre_path %></h4>
</div>

<p><h4>Gêneros cadastrados:</h4></p>

<div>
  <ul>
    <% @genres.each do | genre |%>
      <li>
        <%= link_to genre.name, genre%>
      </li>
    <% end %>
  </ul>    
</div>

<div>
  <%= link_to 'Página inicial', root_path %>
</div>

app/views/genres/new.html.erb
<h2>Cadastro de gêneros</h2>

<div>
  <%= render partial: 'form', locals: { genre: @genre } %>
</div>

<p><%= link_to 'Gêneros', genres_path%></p>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<div>
  <% if flash[:notice] %>

    <div style="margin: 10px 0px">
      <%= flash[:notice] %>
    </div>

  <% end %>
</div>

<div>
    <h3>Descrição:</h3>
    <p><%= @genre.description %></p>
</div>

<div>
  <% if @movies.any?%>
    <p><h3>Filmes deste gênero:</h3></p>
    <%= render partial: 'shared/movie', locals: {movies: @movies} %>
  <% else %>
    <div><h3>Não há filmes deste gênero cadastrados.</h3></div>
    <div><%= link_to 'Cadastre um filme para este gênero', new_movie_path %></div>
  <% end %>
</div>

<p><strong><%= link_to 'Editar gênero', edit_genre_path%></strong></p>

<p><%= link_to 'Gêneros', genres_path%></p>

app/views/home/index.html.erb
<h1>Bem-vindo(a) ao Catálogo de Filmes</h1>

<h3>Escolha a lista que deseja visualisar:</h3>

<ul>
    <li><%= link_to 'Filmes', movies_path%></li>
    <li><%= link_to 'Diretores', directors_path%></li>
    <li><%= link_to 'Gêneros', genres_path%></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Catalogo De Filmes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<div>
  <% if flash[:notice] %>

    <div style="margin: 10px 0px">
      <%= flash[:notice] %>
    </div>

  <% end %>
</div>

<div>
  <%= form_with model: movie do | f | %>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Título: '%>
      <%= f.text_field :name %>
    </div>
    
    <div style="padding-bottom: 10px;">
      <%= f.label 'País de origem: '%>
      <%= f.text_field :country_of_origin %>
    </div>
    
    <div style="padding-bottom: 10px;">
      <%= f.label 'Ano de lançamento: '%>
      <%= f.select :release_year, (1888..(Time.current.year + 3)).to_a.reverse %>
    </div>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Duração: '%>
      <%= f.number_field :length %>
    </div>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Gênero: '%>
      <%= f.collection_select :genre_id, Genre.all, :id, :name %>
    </div>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Diretor: '%>
      <%= f.collection_select :director_id, Director.all, :id, :name %>
    </div>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Status de lançamento: '%>
      <%= f.select :release_status, [['A ser lançado', :upcoming], ['Já lançado', :released]] %>
    </div>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Pôster do filme: '%>
      <%= f.file_field :poster %>
    </div>

    <div style="padding-bottom: 10px;">
      <%= f.label 'Sinopse: '%>
      <%= f.text_area :synopse %>
    </div>

    <p><%= f.submit 'Cadastrar'%></p> 

  <% end %>
</div>

app/views/movies/edit.html.erb
<h2>Editar filme</h2>

<%= render partial: 'form', locals: { movie: @movie }%>

<p><%= link_to 'Cancelar edição', movie_path(@movie) %></p>

app/views/movies/index.html.erb
<h1>Filmes</h1>

<div>
<h4><%= link_to 'Cadastrar novo filme', new_movie_path %></h4>
</div>

<p><h3>Filmes já lançados:</h3></p>

<div>
  <%= render partial: 'shared/movie', locals: { movies: @released_movies}%>
</div>

<br />

<p><h3>Filmes a serem lançados:</h3></p>

<div>
  <%= render partial: 'shared/movie', locals: { movies: @upcoming_movies}%>
</div>

<div>
  <p><%= link_to 'Página inicial', root_path %></p>
</div>

app/views/movies/new.html.erb
<h2>Cadastro de filmes</h2>

<%= render partial: 'form', locals: { movie: @movie }%>

<p><%= link_to 'Filmes', movies_path%></p>

app/views/movies/show.html.erb
<h1><%= @movie.name %></h1>

<div>
  <% if @movie.poster.url %>
    <%= image_tag(@movie.poster.url, width: "250", height: "350") %>
  <% end %>
</div>

<div>
  <h3>Sinopse:</h3>
  <p><%= @movie.synopse%></p>
</div>

<div style="padding-bottom: 10px;">
  <strong>Ano de lançamento:</strong> 
  <%= @movie.release_year %>
</div>

<div style="padding-bottom: 10px;">
  <strong>País de origem:</strong> 
  <%= @movie.country_of_origin %>
</div>

<div style="padding-bottom: 10px;">
  <strong>Duração:</strong> 
  <%= @movie.length %> minutos
</div>

<div style="padding-bottom: 10px;">
  <strong>Ano de lançamento:</strong> 
  <%= @movie.release_year %>
</div>

<div style="padding-bottom: 10px;">
  <strong>Gênero:</strong> 
  <%= link_to @movie.genre.name, genre_path(@movie.genre) %>
</div>

<div style="padding-bottom: 10px;">
  <strong>Diretor(a):</strong> 
  <%= link_to @movie.director.name, director_path(@movie.director) %>
</div>

<div style="padding-bottom: 10px;">
  <strong>Status de lançamento:</strong> 
  <%= @movie.translate_release_status %>
</div>

<div style="padding-bottom: 10px;">
  <strong>Status da publicação:</strong> 
  <%= @movie.translate_status %>
</div>

<div>
  <%= button_to 'Publicar', publish_movie_path, { method: 'patch'} %>
  <br />
  <%= button_to 'Remover publicação', withdraw_publication_movie_path, { method: 'patch'} %>
</div>

<div>
  <p><strong><%= link_to 'Editar filme', edit_movie_path %></strong></p>
</div>
<div>
    <p><%= link_to 'Filmes', movies_path %></p>
</div>

app/views/shared/_movie.html.erb
<div style="display: flex; flex-wrap: wrap; gap: 20px">
  <% movies.each do | movie |%>
    
    <div style="text-align: center;">
      <% if movie.poster.url %>
        <%= link_to image_tag(movie.poster.url, width: "180", height: "250"), movie %>
       
        <div><strong><%= movie.name %></strong></div>
        <div><strong><%= movie.release_year %></strong></div>


      <% else %>

        <strong><%= link_to movie.name, movie %></strong>

      <% end %>
    </div> 
      
  <% end %>
</div>